version: "3.8"

services:
 frontend:
  build:
   context: .
   dockerfile: ./frontend/Dockerfile
  ports:
   - "8080:80"
  depends_on:
   - backend
  volumes:
   - ./frontend:/frontend

 backend:
  build:
   context: .
   dockerfile: ./backend/Dockerfile
  ports:
   - "3000:3000"
  environment:
   - NODE_ENV=production
  volumes:
   - ./backend:/backend
